name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: cd natetrystuff && mvn clean package -DskipTests
        
      - name: List output of build
        run: ls -l natetrystuff/target/

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            sudo systemctl stop natetrystuff-api.service
            cp /apps/natetrystuff-api/natetrystuff-0.0.1-SNAPSHOT.jar /apps/natetrystuff-api/natetrystuff-api.jar
            sudo systemctl start natetrystuff-api.service
