name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: cd natetrystuff && mvn clean package -DskipTests
        
      - name: List output of build
        run: ls -l natetrystuff/target/
      
      - name: List files in the target directory
        run: ls -la ${{ github.workspace }}/natetrystuff/target/

      - name: Setup SSH Known Hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts
      
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
            ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}
        
      - name: Copy JAR to server
        run: scp -v natetrystuff/target/natetrystuff-0.0.1-SNAPSHOT.jar ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }}:/apps/natetrystuff-api/
        
      - name: Restart Service
        run: ssh ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }} ' systemctl restart natetrystuff-api.service'
      