name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: cd natetrystuff && mvn clean package -DskipTests
        
      - name: List output of build
        run: ls -l natetrystuff/target/
      
      - name: List files in the target directory
        run: ls -la ${{ github.workspace }}/natetrystuff/target/

      - name: Copy JAR to server
        run: scp -v ${{ github.workspace }}/natetrystuff/target/natetrystuff-0.0.1-SNAPSHOT.jar ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }}:/apps/natetrystuff-api/
      
      - name: Copy JAR and Service File to DigitalOcean
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Transfer the jar file
            ls
            scp natetrystuff/target/natetrystuff-0.0.1-SNAPSHOT.jar ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }}:/apps/natetrystuff-api/
            
            # Create and transfer the service file
            echo "[Unit]
            Description=Nate Try Stuff API Service
            After=network.target
      
            [Service]
            User=${{ secrets.DROPLET_USERNAME }}
            ExecStart=/usr/bin/java -jar /apps/natetrystuff-api/natetrystuff-0.0.1-SNAPSHOT.jar
            SuccessExitStatus=143
      
            [Install]
            WantedBy=multi-user.target" > natetrystuff-api.service
            scp natetrystuff-api.service ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }}:/etc/systemd/system/
      
      # - name: Enable and Start Service on DigitalOcean
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.DROPLET_HOST }}
      #     username: ${{ secrets.DROPLET_USERNAME }}
      #     key: ${{ secrets.DROPLET_SSH_KEY }}
      #     script: |
      #       # Reload systemd, enable and start the service
      #       sudo systemctl daemon-reload
      #       sudo systemctl enable natetrystuff-api.service
      #       sudo systemctl start natetrystuff-api.service
      